version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_deploy_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=project_dev
      - POSTGRES_USER=username_dev
      - POSTGRES_PASSWORD=password_dev
      
  web:
    build: ./project
    container_name: web_deploy_dev
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/project/
    ports:
      - 8000:8000
    env_file:
      - ./env/dev/project.env
    depends_on:
      - db

volumes:
  postgres_data: