# Generated by Django 4.2.6 on 2023-10-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='order',
            field=models.IntegerField(auto_created=True, default=0, verbose_name='Order #'),
        ),
    ]
