# Generated by Django 4.2.4 on 2023-09-04 20:46

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Last Modified')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Creation Date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=32767, verbose_name='Description')),
                ('slug', models.CharField(max_length=255, null=True, validators=[core.models.validate_slug], verbose_name='Slug')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Last Modified')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Creation Date')),
                ('order', models.IntegerField(auto_created=True, default=-1, editable=False, verbose_name='Current Revision')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(blank=True, default='', max_length=32767, verbose_name='Description')),
                ('slug', models.CharField(max_length=255, validators=[core.models.validate_slug], verbose_name='Slug')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'Page',
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('flags', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Text',
                'db_table': 'TextContent',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Last Modified')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Creation Date')),
                ('rollback', models.BooleanField(auto_created=True, default=False, editable=False, verbose_name='Is Rollback?')),
                ('order', models.IntegerField(auto_created=True, default=0, editable=False, verbose_name='Order #')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.textcontent', verbose_name='Text Content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='core.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'db_table': 'Revision',
            },
        ),
    ]
